[[main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[main]]
name = "Posts"
weight = 200
identifier = "posts"
url = "/post/"

[[main]]
name = "Project"
weight = 300
identifier = "project"
url = "/about/"

[[main]]
name = "Blog"
weight = 300
identifier = "Blog"
url = "/Blog/"

[[main]]
name = "Contact"
weight = 400
identifier = "contact"
url = "/contact/"

[[footer]]
name = "imprint"
weight = 1
identifier = "imprint"
url = "/imprint/"
